modLoader="javafml"
loaderVersion="[48,)"
issueTrackerURL="https://github.com/MattCzyr/NaturesCompass/issues"
license="CC BY-NC-SA 4.0"

[[mods]]
    modId="naturescompass"
    version="1.20.2-1.11.3-forge"
    displayName="Nature's Compass"
    displayURL="https://github.com/MattCzyr/NaturesCompass"
    authors="ChaosTheDude"
    description='''
    Search for a biome and get information about it.
    '''

[[dependencies.naturescompass]]
    modId="forge"
    mandatory=true
    versionRange="[48,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.naturescompass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,)"
    ordering="NONE"
    side="BOTH"
