modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/MattCzyr/NaturesCompass/issues"
license="CC BY-NC-SA 4.0"

[[mods]]
    modId="naturescompass"
    version="${file.jarVersion}"
    displayName="Nature's Compass"
    displayURL="https://github.com/MattCzyr/NaturesCompass"
    authors="ChaosTheDude"
    description='''
    Search for a biome and get information about it.
    '''

[[dependencies.naturescompass]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.naturescompass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"
